Name = "Liquid Web"
Description = '''
A DNS solver using Liquid Web's Storm API. 
'''
URL = "https://cart.liquidweb.com/storm/api/docs/v1/"
Code = "liquidweb"
Since = "v3.1.0"

Example = '''
LIQUID_WEB_URL="https://api.stormondemand.com" \
LIQUID_WEB_USERNAME=someuser \
LIQUID_WEB_PASSWORD="somepass" \
LIQUID_ZONE=tacoman.com.net \
lego --dns liquidweb --email someaccount@email.com --domains "foo.email.com" run
'''

[Configuration]
  [Configuration.Credentials]
    LIQUID_WEB_USERNAME = "Storm API Username"
    LIQUID_WEB_PASSWORD = "Storm API Password"
  [Configuration.Additional]
    LIQUID_WEB_URL = "Storm API endpoint"
    LIQUID_WEB_ZONE = "DNS Zone"
    LIQUID_WEB_TIMEOUT = "Maximum waiting time for the DNS records to be created (not verified)"
    LIQUID_WEB_POLLING_INTERVAL = "Time between DNS propagation check"
    LIQUID_WEB_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"

[Links]
  API = "https://cart.liquidweb.com/storm/api/docs/v1/"
