Name = "Liquid Web"
Description = ''''''
URL = "https://cart.liquidweb.com/storm/api/docs/v1/"
Code = "liquidweb"
Since = "v3.1.0"

Example = ''''''

[Configuration]
  [Configuration.Credentials]
    LW_USERNAME = "Storm API Username"
    LW_PASSWORD = "Storm API Password"
  [Configuration.Additional]
    LW_URL = "Storm API endpoint"
    LW_ZONE = "DNS Zone"
    LW_TIMEOUT = "Maximum waiting time for the DNS records to be created (not verified)"

[Links]
  API = "https://cart.liquidweb.com/storm/api/docs/v1/"
